### ISSUE TITLE
Merge ESlint:Master to upgrade!

### ISSUE THREAD

**Issue by abritinthebay** [codeclimate/eslint#10]
This is massively far behind in features and tooling support.

**Comment by dblandin** [comment]
Hi @abritinthebay,

Thanks for testing out the new ESLint v2 channel yesterday! That new channel pulls in ESLint directly from NPM instead of this GH repo, so keeping up with new features/tooling should be far easier moving forward.

https://github.com/codeclimate/codeclimate-eslint/pull/92 represents the current state of the `eslint-2` channel.

I'm going to close this issue but feel free to direct any questions regarding ESLint v2 support to that PR. We'll be working towards updating the supported ESLint plugins shortly. Thanks!

**Comment by abritinthebay** [comment]
So far it works with the updates to the yml so yay! 👍
